name: iOS pod CI

on:
  release:
    types: [published]
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Deploy to CocoapodsPre
      run: |
        set -eo pipefail
        
        temptag=$(git describe --tags `git rev-list --tags --max-count=1`)
        VERSION=${temptag#*v}
        echo $VERSION
        export LIB_VERSION=$VERSION
                
        pod lib lint --verbose --allow-warnings --use-libraries
        pod trunk push --verbose --allow-warnings --use-libraries
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.IOT_COCOAPODS_TRUNK_TOKEN }}
